<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Ahmad.Mafia.Application.Contract\Ahmad.Mafia.Application.Contract.csproj" />
    <ProjectReference Include="..\..\Application\Ahmad.Mafia.Application.Query\Ahmad.Mafia.Application.Query.csproj" />
    <ProjectReference Include="..\..\Application\Ahmad.Mafia.Application.Validators\Ahmad.Mafia.Application.Validators.csproj" />
    <ProjectReference Include="..\..\Domain\Ahmad.Mafia.Domain\Ahmad.Mafia.Domain.csproj" />
    <ProjectReference Include="..\Ahmad.Mafia.Persistence.EF\Ahmad.Mafia.Persistence.EF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AhmadBase.Config" Version="1.0.7" />
    <PackageReference Include="AhmadBase.Web" Version="1.0.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- WebBuilder.ConfigureAutofac() از AhmadBase.Config این اسمبلی رو با اسم {CompanyName}.{ContextName}.Config بار می‌کنه -->
    <AssemblyName>Ahmad.Mafia.Config</AssemblyName>
  </PropertyGroup>

</Project>
