<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Ahmad.Mafia.Application.Contract\Ahmad.Mafia.Application.Contract.csproj" />
    <ProjectReference Include="..\..\Application\Ahmad.Mafia.Application.Query.Contract\Ahmad.Mafia.Application.Query.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AhmadBase.Web" Version="1.0.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- WebBuilder.ConfigureController() از AhmadBase.Config این اسمبلی رو با اسم {CompanyName}.{ContextName}.Rest بار می‌کنه -->
    <AssemblyName>Ahmad.Mafia.Rest</AssemblyName>
  </PropertyGroup>

</Project>
